### ISSUE TITLE
[Bug]: PinApp doesn't load list of installed apps

### ISSUE THREAD

**Issue by kutzlect** [fabrialberio/PinApp#10]
### Describe the bug
PinApp doesn't load in list of installed apps.

 ### To Reproduce
1. Launch 'PinApp'
2. Switch to 'Installed' tab
3. Wait for list to load
4. PinApp keeps 'Loading apps...'

### Screenshots
![image](https://user-images.githubusercontent.com/76667488/208312659-49773280-5449-408a-b274-2ea74f28543f.png)

### Linux distribution
Distro: Fedora Silverblue 37
DE: GNOME 43

### Additional context
```
Exception in thread Thread-2 (target):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/PinApp/pinapp/folders.py", line 51, in target
    self.get_files(sort)
  File "/app/share/PinApp/pinapp/folders.py", line 47, in get_files
    if sort: self.files = sorted(self.files)
  File "/app/share/PinApp/pinapp/desktop_entry.py", line 429, in __lt__
    self.load()
  File "/app/share/PinApp/pinapp/desktop_entry.py", line 413, in load
    super().load()
  File "/app/share/PinApp/pinapp/desktop_entry.py", line 348, in load
    self.parser.read(self.path)
  File "/usr/lib/python3.10/configparser.py", line 698, in read
    self._read(fp, filename)
  File "/usr/lib/python3.10/configparser.py", line 1097, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from PosixPath('/var/lib/flatpak/exports/share/applications/org.mozilla.firefox.desktop') [line 160]: option 'Keywords' in section 'Desktop Entry' already exists
```

**Comment by fabrialberio** [comment]
The cause of the error is a .desktop file with duplicate keys (`/var/lib/flatpak/exports/share/applications/org.mozilla.firefox.desktop`). Fixed it in 18311ff7d70a70df1fda987d31c99c2a5feaf900.

If you don't want to wait for the app to update, you can just open the file and remove one of the lines that start with `Keywords = ...`
